version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: .
    binary: gitea-config-wave
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - files:
      - README.md
      - LICENSE*

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'
      - Merge pull request
      - Merge branch

brews:
  - name: gitea-config-wave
    homepage: "https://github.com/DUALSTACKS/gitea-config-wave"
    description: "CLI tool to manage Gitea repository settings at scale"
    repository:
      owner: DUALSTACKS
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    install: |
      bin.install "gitea-config-wave"
    test: |
      system "#{bin}/gitea-config-wave --version"

# Temporarily commenting out Docker configuration
# dockers:
#   - image_templates:
#       - "ghcr.io/dualstacks/gitea-config-wave:{{ .Version }}"
#       - "ghcr.io/dualstacks/gitea-config-wave:latest"
#     dockerfile: Dockerfile.goreleaser
#     build_flag_templates:
#       - "--label=org.opencontainers.image.created={{.Date}}"
#       - "--label=org.opencontainers.image.title={{.ProjectName}}"
#       - "--label=org.opencontainers.image.revision={{.FullCommit}}"
#       - "--label=org.opencontainers.image.version={{.Version}}"
