config:
  # # Directory where the pulled config will be saved and from there it can be adjusted and pushed to the target repos; this will also allow people to have different config dumps for different repoes or groups of repoes
  output_dir: .gitea/defaults

targets:
  autodiscover: true # if true, autodiscover repos from the organization
  autodiscover_filter: "*" # filter for autodiscover
  repos: [] # explicit list of repos to target; if both autodiscover and repos are set, they will be merged
  exclude_repos: [] # list of repo names to exclude

dry_run: false
topics_update_strategy: "override" # possible values: "override", "merge"
branch_protections_update_strategy: "override" # possible values: "override", "merge"
