config:
  # where the setting files are stored
  output_dir: .gitea/defaults

# what to pull from the target repos
pull:
  repo_settings: true
  topics: true
  branch_protections: true
  tag_protections: true
  webhooks: true
  templates: true

# what to push to the target repos
push:
  repo_settings: true
  topics: true
  branch_protections: true
  tag_protections: true
  webhooks: true
  templates: true

targets:
  autodiscover: true # if true, autodiscover repos from the organization
  organization: "DUALSTACKS" # name of the Gitea organization for autodiscovery
  autodiscover_filter: "*" # filter to autodiscover repos in the organization; e.g. "*" to autodiscover all repos

  # explicit list of full-names of repos to target; if both autodiscover and repos are set,
  # they will be merged, e.g. ["ORG/repo1", "ORG/repo2"]
  repos: []
  exclude_repos: [] # list of full-names of repos to exclude; e.g. ["ORG/repo3", "ORG/repo4"]


# Update strategies:
#
# replace: Wipe remote branch protections entirely and push YAML config as full new state

# append:  Only add branch protections from YAML config that don't yet exist remotely,
#         without modifying or deleting current branch protections

# merge:   Only add branch protections from YAML that don't yet exist remotely,
#         without modifying or deleting current branch protections
branch_protections_update_strategy: "merge" # -> supported: replace, merge, append
tag_protections_update_strategy: "append" # -> supported: replace, merge, append
topics_update_strategy: "append" # -> supported: replace, append
webhooks_update_strategy: "append" # -> supported: replace, merge, append
